config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  resources :champions

end

app/models/champion.rb
class Champion < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/champions_controller.rb
class ChampionsController < ApplicationController
  before_action :set_champion, only: [:show, :edit, :update, :destroy]

  # GET /champions
  # GET /champions.json
  def index
    @champions = Champion.all
  end

  # GET /champions/1
  # GET /champions/1.json
  def show
  end

  # GET /champions/new
  def new
    @champion = Champion.new
  end

  # GET /champions/1/edit
  def edit
  end

  # POST /champions
  # POST /champions.json
  def create
    @champion = Champion.new(champion_params)

    respond_to do |format|
      if @champion.save
        format.html { redirect_to @champion, notice: 'Champion was successfully created.' }
        format.json { render :show, status: :created, location: @champion }
      else
        format.html { render :new }
        format.json { render json: @champion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /champions/1
  # PATCH/PUT /champions/1.json
  def update
    respond_to do |format|
      if @champion.update(champion_params)
        format.html { redirect_to @champion, notice: 'Champion was successfully updated.' }
        format.json { render :show, status: :ok, location: @champion }
      else
        format.html { render :edit }
        format.json { render json: @champion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /champions/1
  # DELETE /champions/1.json
  def destroy
    @champion.destroy
    respond_to do |format|
      format.html { redirect_to champions_url, notice: 'Champion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_champion
      @champion = Champion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def champion_params
      params.require(:champion).permit(:riot_id, :name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/champions_helper.rb
module ChampionsHelper
end

app/views/champions/_form.html.erb
<%= form_for(@champion) do |f| %>
  <% if @champion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@champion.errors.count, "error") %> prohibited this champion from being saved:</h2>

      <ul>
      <% @champion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :riot_id %><br>
    <%= f.number_field :riot_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/champions/edit.html.erb
<h1>Editing Champion</h1>

<%= render 'form' %>

<%= link_to 'Show', @champion %> |
<%= link_to 'Back', champions_path %>

app/views/champions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Champions</h1>

<table>
  <thead>
    <tr>
      <th>Riot</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @champions.each do |champion| %>
      <tr>
        <td><%= champion.riot_id %></td>
        <td><%= champion.name %></td>
        <td><%= link_to 'Show', champion %></td>
        <td><%= link_to 'Edit', edit_champion_path(champion) %></td>
        <td><%= link_to 'Destroy', champion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Champion', new_champion_path %>

app/views/champions/new.html.erb
<h1>New Champion</h1>

<%= render 'form' %>

<%= link_to 'Back', champions_path %>

app/views/champions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Riot:</strong>
  <%= @champion.riot_id %>
</p>

<p><%= image_tag @champion.icon_url %></p>

<p>
  <strong>Name:</strong>
  <%= @champion.name %>
</p>

<%= link_to 'Edit', edit_champion_path(@champion) %> |
<%= link_to 'Back', champions_path %>

app/views/home/index.html.erb
<h1>Nurf the Meta</h1>
<% Champion.all.each do |champ| %>
<span class="champion">
    <%= link_to image_tag(champ.icon_url).html_safe, champ %>
</span>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Nurf the Meta" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="row">
        <%= yield %>
    </div>

  </body>
</html>